### ISSUE TITLE
Use WiFi instead of Bluetooth Communication

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/Earthquake_Detection#2]
## Note

This issue is blocked by issue #1. You cannot work on this issue without that issue being solved already. If you want to work on this and that issue hasn't been solved, feel free to go ahead and solve that issue too. These are high value PRs and are highly encouraged!

## About

Once the hardware has been implemented on a NodeMCU, convert the bluetooth communication into an HTTP client. This client is supposed to send a `GET` request to a server whenever an earthquake is detected. Bonus points if you send a `POST` request instead along with some metadata about that particular module. You can hardcode the metadata for the hardware module. The URL for the server will be given to you by the maintainer

**Comment by avaneeshmahendra29** [comment]
can i assigned?

**Comment by bun137** [comment]
yepp assigned!

**Comment by anuragrao04** [comment]
Please approach the maintainer for the hardware

**Comment by komulannister** [comment]
can i get assigned?

**Comment by bun137** [comment]
@avaneeshmahendra29 please open a draft pr, its been over 30 mins of assignment

**Comment by avaneeshmahendra29** [comment]
@bun137 I am no longer working on this

**Comment by bun137** [comment]
@komulannister you can start working on this!, but note that this issue cant be solved without solving issue #1 . can I assign you to issue #1?

**Comment by KunalMaverick** [comment]
is this assigned?

**Comment by bun137** [comment]
@KunalMaverick this issue cant be solved without solving issue #1. lmk if you want to be assigned to issue #1!

**Comment by samarth777** [comment]
assign this to me

**Comment by bun137** [comment]
@samarth777 sorry, just assigned another contributor to issue #1

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by bun137** [comment]
@samarth777 you have been assigned, please approach the maintainer or open a draft PR in 30 mins to show your progress!
